// This file was generated by silverstripe/tx-translator from client/lang/src/en.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "ColorPickerField.EMPTY_TITLE": "None",
    "ColorPickerField.SEARCH_BLOCKS": "Search colours",
    "FontPickerField.EMPTY_TITLE": "None",
    "FontPickerField.PREVIEW_FONT_ALPHABET": "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz 0123456789 - = _ + < > ? / . , : \"",
    "FontPickerField.PREVIEW_FONT_SENTENCE": "The quick brown fox jumps over the lazy dog."
});
}