// This file was generated by silverstripe/tx-translator from client/lang/src/eo.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('eo', {
    "ColorPickerField.EMPTY_TITLE": "Neniu",
    "ColorPickerField.SEARCH_BLOCKS": "Serĉaj koloroj",
    "FontPickerField.EMPTY_TITLE": "Neniu",
    "FontPickerField.PREVIEW_FONT_ALPHABET": "AaBbCcĈĉDdEeFfGgĜĝHhĤĥIiJjĴĵKkLlMmNnOoPpQqRrSsŜŝTtUuŬŭVvWwXxYyZz 0123456789 - = _ + < > ? / . , : \"",
    "FontPickerField.PREVIEW_FONT_SENTENCE": "Ĉi-ĵaŭde ŝi havigu informojn pri biciklista ĝazo-ĥoro."
});
}