---
Name: agencyextensionsconfig
---
CWP\CWP\PageTypes\BaseHomePage:
  extensions:
    - CWP\AgencyExtensions\Extensions\CarouselPageExtension

PageController:
  extensions:
    - CWP\AgencyExtensions\Extensions\CWPPageExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - CWP\AgencyExtensions\Extensions\CWPSiteConfigExtension

---
Name: agencyextensionsresources
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "cwp/agency-extensions:client/dist/styles/bundle.css"
  extra_requirements_javascript:
    - "cwp/agency-extensions:client/dist/js/bundle.js"

---
Name: agencyextensionsfontawesome
Only:
  envvarset: CWP_AGENCY_ENABLE_FONTAWESOME_STYLES
---
SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
